name: Terragrunt Plan on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials using GitHub Secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install Terraform (if not already installed)
      - name: Set Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.5"

      # Step 4: Set up Terragrunt and run init
      - name: Set up Terragrunt and run init
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          terraform_subcommand: "init"
          terragrunt_subcommand: "run-all init"

      # Step 5: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 6: Create virtual environment and install boto3
      - name: Create virtual environment and install boto3
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install boto3

      # Step 7: Zip the Python file
      - name: Zip the Python file
        working-directory: ./lambda
        run: |
          source ../venv/bin/activate
          zip -r lambda_function_payload.zip lambda_function.py

      # Step 8: Initialize Terragrunt
      - name: Terragrunt Init
        working-directory: ./Env
        run: terragrunt run-all init

      # Step 9: Run Terraform Plan with Terragrunt
      - name: Run Terraform Plan
        working-directory: ./Env
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          terraform_subcommand: "plan"
          terragrunt_subcommand: "run-all plan -lock=false"

      # Step 10: Apply Terraform Changes (optional)
      # - name: Run Terraform Apply
      #   run: terragrunt run-all apply -auto-approve -lock=false
