name: Terragrunt Plan on Pull Request

on:
  pull_request:
    branches:
      - main  # Trigger this workflow for pull requests targeting the 'main' branch

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: ./Env  # Default working directory for all steps (Env)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials using GitHub Secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set your desired AWS region

      # Step 3: Install Terraform (if not already installed)
      - name: Set Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.5"

      # Step 4: Set up Terragrunt
      - name: Set up Terragrunt
        uses: the-commons-project/terragrunt-github-actions@1.0.6

      # Step 5: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Set the Python version you need (e.g., 3.8)

      # Step 6: Create virtual environment and install boto3
      - name: Create virtual environment and install boto3
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install boto3

      # Step 7: Zip the Python file (in the lambda directory)
      - name: Zip the Python file
        working-directory: ./lambda  # Run the zip step inside the lambda directory
        run: |
          source ../venv/bin/activate  # Activate the venv if needed
          zip -r lambda_function_payload.zip lambda_function.py

      # Step 8: Initialize Terragrunt
      - name: Terragrunt Init
        working-directory: ./Env
        run: terragrunt run-all init

      # Step 9: Run Terraform Plan
      - name: Run Terraform Plan
        working-directory: ./Env
        run: terragrunt run-all plan -lock=false

      # # Step 10: Apply Terraform Changes (optional, cautious step)
      # - name: Run Terraform Apply
      #   run: terragrunt run-all apply -auto-approve -lock=false
